base:
  'delight':
    - awscli
    - chromium
    - cloud-sql-proxy
    - debian
    - deja-dup
    - firmware-linux-nonfree
    - git
    - google-cloud-sdk
    - hub
    - kube-ps1
    - kubectx
    - k9s
    - mariadb-client
    - minikube
    - plymouth
    - salt-minion
    - spotify
    - terraform
    - terragrunt
    - tig
    - tilix
    - tlp
    - vagrant
    - virtualbox
